# Generated by Django 5.2.3 on 2025-12-14 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_myuser_profile_image_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='desciption',
            new_name='description',
        ),
    ]
